kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lease-access-role
  namespace: lease-demo
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lease-demo-sa
  namespace: lease-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lease-demo-binding
  namespace: lease-demo
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lease-access-role
subjects:
- kind: ServiceAccount
  name: lease-demo-sa
  namespace: lease-demo