apiVersion: apps/v1
kind: Deployment
metadata:
  name: ready-live-example
spec:
  selector:
    matchLabels:
      app: ready-live-example
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ready-live-example
    spec:
      containers:
      - name: ready-live-test
        image: thegoodguym/ready-live-example:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3
          timeoutSeconds: 3
        livenessProbe:
          failureThreshold: 30
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 1
          timeoutSeconds: 1
        env:
          - name: FAIL_READY
            value: "True"
          - name: FAIL_LIVE
            value: "False"
