---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - demo.thegoodguy.io
  resources:
  - echoservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.thegoodguy.io
  resources:
  - echoservers/finalizers
  verbs:
  - update
- apiGroups:
  - demo.thegoodguy.io
  resources:
  - echoservers/status
  verbs:
  - get
  - patch
  - update
