apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx-demo-chart
  namespace: default
spec:
  interval: 2m
  timeout: 1m
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
  releaseName: flux-nginx-demo
  install:
    remediation:
      retries: 1
  upgrade:
    remediation:
      retries: 1
  test:
    enable: true
  driftDetection:
    mode: enabled