apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.0
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
  strategy:
    blueGreen: 
      activeService: nginx-service-active
      previewService: nginx-service-preview
      autoPromotionEnabled: true
      autoPromotionSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-active
spec:
  selector:
    app: nginx
  ports:
  - name: nginx-default-port
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-preview
spec:
  selector:
    app: nginx
  ports:
  - name: nginx-default-port
    protocol: TCP
    port: 80
    targetPort: 80
