apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  selector:
    matchLabels:
      app: chat-app
  replicas: 1
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: chat-test:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: https
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app
spec:
  selector:
    app: chat-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
